---
  - name: install prerequisites
    apt: name=python-boto state=latest update_cache=true cache_valid_time=3600

  - name: acquire certificate from s3
    become: false
    connection: local
    s3:
      region: "{{ s3_ssl_certs_region }}"
      bucket: "{{ s3_ssl_certs_bucket }}"
      aws_access_key: "{{ s3_ssl_certs_accesskey }}"
      aws_secret_key: "{{ s3_ssl_certs_secretkey }}"
      object: "{{ s3_ssl_certs_container }}"
      dest: "{{ s3_ssl_certs_tmpdir }}/{{ s3_ssl_certs_container }}"
      mode: "get"
      overwrite: yes
    changed_when: false

  - name: load certificate data
    become: false
    connection: local
    include_vars:
      file: "{{ s3_ssl_certs_tmpdir }}/{{ s3_ssl_certs_container }}"
      name: certificate

  - name: check if container has good common name
    fail:
      msg: "CN is not defined in {{ s3_ssl_certs_container }}"
    when: certificate.cn is not defined

  - name: check if container has certificate
    fail:
      msg: "Certificate is not defined in {{ s3_ssl_certs_container }}"
    when: certificate.certificate is not defined

  - name: check if container has private key
    fail:
      msg: "Private key is not defined in {{ s3_ssl_certs_container }}"
    when: certificate.private_key is not defined
